name: build
on: 
  push:
    branches:
      - 'current'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v1
    - name: Set up Java 20
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '20'
    - name: Build with Maven
      run: mvn -B --ntp package
  azure-blob: 
    runs-on: 'ubuntu-latest'
    steps: 
    - uses: 'azure/login@v1'
      with: 
        allow-no-subscriptions: 'true'
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
    - uses: 'actions/checkout@v2'
    - name: Set up Java 20
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '20'
    - name: Build with Maven
      run: |
        mvn clean install
        cd azure-blob
        mvn -P azure -amd clean install
